version: "3.9"
services:
  movie:
    build: services/movie/
    ports:
      - "3001:3001"
  booking:
    build: services/booking/
    ports:
      - "3002:3002"
    depends_on:
      - showtime

  showtime:
    build: services/showtime/
    ports:
      - "3003:3003"

  user:
    build: services/user/
    ports:
      - "3004:3004"
    depends_on:
      - booking
      - movie