# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import base_pb2 as protos_dot_base__pb2
from protos import booking_pb2 as protos_dot_booking__pb2
from protos import user_pb2 as protos_dot_user__pb2


class UserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllUsers = channel.unary_stream(
                '/User/GetAllUsers',
                request_serializer=protos_dot_base__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_user__pb2.UserItem.FromString,
                )
        self.GetUserById = channel.unary_unary(
                '/User/GetUserById',
                request_serializer=protos_dot_base__pb2.UserID.SerializeToString,
                response_deserializer=protos_dot_user__pb2.UserItem.FromString,
                )
        self.GetUserBookings = channel.unary_unary(
                '/User/GetUserBookings',
                request_serializer=protos_dot_base__pb2.UserID.SerializeToString,
                response_deserializer=protos_dot_booking__pb2.BookingData.FromString,
                )


class UserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserBookings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllUsers': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllUsers,
                    request_deserializer=protos_dot_base__pb2.Empty.FromString,
                    response_serializer=protos_dot_user__pb2.UserItem.SerializeToString,
            ),
            'GetUserById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserById,
                    request_deserializer=protos_dot_base__pb2.UserID.FromString,
                    response_serializer=protos_dot_user__pb2.UserItem.SerializeToString,
            ),
            'GetUserBookings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserBookings,
                    request_deserializer=protos_dot_base__pb2.UserID.FromString,
                    response_serializer=protos_dot_booking__pb2.BookingData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'User', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class User(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/User/GetAllUsers',
            protos_dot_base__pb2.Empty.SerializeToString,
            protos_dot_user__pb2.UserItem.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/User/GetUserById',
            protos_dot_base__pb2.UserID.SerializeToString,
            protos_dot_user__pb2.UserItem.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/User/GetUserBookings',
            protos_dot_base__pb2.UserID.SerializeToString,
            protos_dot_booking__pb2.BookingData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
