# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/showtime.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import base_pb2 as protos_dot_base__pb2
from protos import movie_pb2 as protos_dot_movie__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protos/showtime.proto\x1a\x11protos/base.proto\x1a\x12protos/movie.proto\"\x14\n\x04\x44\x61te\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"9\n\x08Schedule\x12\x13\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x05.Date\x12\x18\n\x06movies\x18\x02 \x03(\x0b\x32\x08.MovieID2S\n\x08Showtime\x12%\n\x0fGetMoviesByDate\x12\x05.Date\x1a\t.Schedule\"\x00\x12 \n\x08GetTimes\x12\x06.Empty\x1a\x08.MovieID\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.showtime_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATE._serialized_start=64
  _DATE._serialized_end=84
  _SCHEDULE._serialized_start=86
  _SCHEDULE._serialized_end=143
  _SHOWTIME._serialized_start=145
  _SHOWTIME._serialized_end=228
# @@protoc_insertion_point(module_scope)
