# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import base_pb2 as protos_dot_base__pb2
from protos import movie_pb2 as protos_dot_movie__pb2
from protos import showtime_pb2 as protos_dot_showtime__pb2


class ShowtimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMoviesByDate = channel.unary_unary(
                '/Showtime/GetMoviesByDate',
                request_serializer=protos_dot_showtime__pb2.Date.SerializeToString,
                response_deserializer=protos_dot_showtime__pb2.Schedule.FromString,
                )
        self.GetTimes = channel.unary_stream(
                '/Showtime/GetTimes',
                request_serializer=protos_dot_base__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_movie__pb2.MovieID.FromString,
                )


class ShowtimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMoviesByDate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShowtimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMoviesByDate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMoviesByDate,
                    request_deserializer=protos_dot_showtime__pb2.Date.FromString,
                    response_serializer=protos_dot_showtime__pb2.Schedule.SerializeToString,
            ),
            'GetTimes': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTimes,
                    request_deserializer=protos_dot_base__pb2.Empty.FromString,
                    response_serializer=protos_dot_movie__pb2.MovieID.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Showtime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Showtime(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMoviesByDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Showtime/GetMoviesByDate',
            protos_dot_showtime__pb2.Date.SerializeToString,
            protos_dot_showtime__pb2.Schedule.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTimes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Showtime/GetTimes',
            protos_dot_base__pb2.Empty.SerializeToString,
            protos_dot_movie__pb2.MovieID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
