---
openapi: 3.0.0
info:
  title: Showtime API
  description: This is the API of the Showtime service
  contact:
    email: helene.coullon@imt-atlantique.fr
  license:
    name: GPL v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.0.0
servers:
  - url: https://virtserver.swaggerhub.com/UE-archi-distribuees/Showtime/1.0.0
    description: SwaggerHub API Auto Mocking
  - url: https://virtserver.swaggerhub.com/UE-archi-distribuees/Movie/1.0.0
    description: SwaggerHub API Auto Mocking
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  /:
    get:
      tags:
        - developers
      summary: home page of the service
      description: |
        Nothing to do
      operationId: home
      responses:
        "200":
          description: welcome message
          content:
            text/html:
              schema:
                type: string
                example: <h1>Test</h1>
  /users:
    get:
      tags:
        - developers
      summary: get the full JSON database
      description: |
        Nothing to do
      operationId: get_users
      responses:
        "200":
          description: full JSON
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AllUser"
  /users/{userid}:
    get:
      tags:
        - developers
      summary: get the user by ID
      description: |
        Get the user for a given ID
      operationId: get_user_byid
      parameters:
        - name: userid
          in: path
          description: date.
          required: true
          style: simple
          explode: false
          schema:
            maximum: 1
            minimum: 1
            type: string
      responses:
        "200":
          description: User
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: bad input parameter
    post:
      tags:
        - admins
      summary: add a user
      description: Adds a user to the system
      operationId: create_user
      parameters:
        - name: userid
          in: path
          description: USER ID.
          required: true
          style: simple
          explode: false
          schema:
            maximum: 1
            minimum: 1
            type: string
      requestBody:
        description: User item to add
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewUser"
      responses:
        "200":
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewUser"
        "409":
          description: an existing item already exists
  /booking/{userid}:
    get:
      tags:
        - developers
      summary: get all the booking dates made by the user
      description: |
        Get the booking date of an user given its ID
      operationId: get_users_booking
      parameters:
        - name: userid
          in: path
          description: date.
          required: true
          style: simple
          explode: false
          schema:
            maximum: 1
            minimum: 1
            type: string
      responses:
        "200":
          description: Dates
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Dates"
        "400":
          description: bad input
  /allmoviesbooked/{userid}:
    get:
      summary: get all the movies that the user booked
      description: |
        Get all the movies that the user booked given its ID
      operationId: get_all_movies_booked
      parameters:
        - name: userid
          in: path
          description: date.
          required: true
          style: simple
          explode: false
          schema:
            maximum: 1
            minimum: 1
            type: string
      responses:
        "200":
          description: Movies
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Movies"
        "400":
          description: bad input

components:
  schemas:
    AllUser:
      required:
        - user
      type: object
      properties:
        user:
          type: array
          items:
            $ref: "#/components/schemas/User"
    User:
      required:
        - id
        - name
        - last_active
      type: object
      properties:
        name:
          type: string
          example: "Jean Eustache"
        id:
          type: string
          example: "jean_eustache"
        last_active:
          type: string
          example: "1360031222"
    NewUser:
      required:
        - id
        - name
      type: object
      properties:
        name:
          type: string
          example: "Jean Eustache"
        id:
          type: string
          example: "jean_eustache"
    DateItem:
      required:
        - date
        - movies
      type: object
      properties:
        date:
          type: string
          example: "20151201"
        movies:
          type: array
          items:
            type: string
            example: 276c79ec-a26a-40a6-b3d3-fb242a5947b6
    Dates:
      type: array
      items:
        $ref: "#/components/schemas/DateItem"

    MovieItem:
      required:
        - director
        - rating
        - title
        - id
      type: object
      properties:
        title:
          type: string
          example: The Martian
        rating:
          type: string
          example: "7"
        director:
          type: string
          example: Paul McGuigan
        id:
          type: string
          example: 39ab85e5-5e8e-4dc5-afea-65dc368bd7ab

    Movies:
      type: array
      items:
        $ref: "#/components/schemas/MovieItem"
